### PR TITLE
Nc 22 create base html

### PR DESCRIPTION
**Pull request by nataliacza**
Updates:
- change urls in music_collection
- create draft for basic templates - base, 404, about us, home
- create music.urls
- delete endfor in cd-list template

### CODE REVIEW

**Comment by blazejpsz** [comment]
looks good - nothing to change

**Review by KN-9 — APPROVED** [review]
Ok

**Review by Lewer95 — APPROVED** [review]
good job

**Comment by KateuszMacprzak** [comment]
i believe it's ok

**Pull request merged**
