### PR TITLE
Init Django project

### PR DESCRIPTION
**Pull request by Lewer95**
Project boilerplate

### CODE REVIEW

**Review by KN-9 — APPROVED** [review]
Ok

**Review by KateuszMacprzak — APPROVED** [review]
Good one

**Comment by SDAgrupa1** [comment]
Awesome

**Comment by nataliacza** [comment]
All good

**Review by nataliacza — APPROVED** [review]
OK

**Review by blazejpsz — APPROVED** [review]
Great job !

**Pull request merged**
