### PR TITLE
BK-01-Register

### PR DESCRIPTION
**Pull request by Lewer95**
Deleted custom register from branch BK-1-Add User 
Added standard Django registration and login form 
Changes in Urls Changes in Settings 
And a lot of interesting stuff

Read it and have fun to try understand whole changes 👍

### CODE REVIEW

**Comment by blazejpsz** [comment]
looks great !

**Review by KN-9 — APPROVED** [review]
Ok

**Review by nataliacza — APPROVED** [review]
All good!

**Comment by KateuszMacprzak** [comment]
In my eyes it's ok

**Pull request merged**
